spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budgeting_app
    username: budgeting_user
    password: securepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: password
    enabled: false
server:
  port:8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG
