spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budgeting_app
    username: budgeting_user
    password: securepassword
    driver-class-name: org.postgresql.Driver
    
  security:
    enabled: false
    user:
      name: admin
      password: admin # Optional: Default credentials if you still want basic auth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: DEBUG


# Management (optional for Actuator health/info endpoints)
management:
  endpoints:
    web:
      exposure:
        include: health, info
